### ISSUE TITLE
Missing some legends

### ISSUE THREAD

**Issue by andre-carvalho** [Terrabrasilis/webmap#16]
Some English legends are missing, for example:
 > For the Legal Amazon, the Layer [Image Mosaic - 2000/2018](http://terrabrasilis.dpi.inpe.br/geoserver/ows?request=GetLegendGraphic&format=image/png&width=20&height=20&layer=prodes-legal-amz:temporal_mosaic_legal_amazon_2000_2018&service=WMS&style=temporal_mosaic_legal_amazon_2000_2018_en)

**Comment by PauloLuan** [comment]
Affected layers:

- (Amazon) Yearly Deforestation - 2008/2018
- (Amazon) Image Mosaic - 2000/2018
- (Legal Amazon) Image Mosaic - 2000/2018

**Comment by PauloLuan** [comment]
Fixed
