### ISSUE TITLE
Add temporal filter to layer

### ISSUE THREAD

**Issue by claudiobogossian** [terrabrasilis/webmap#25]
Add a tool to filter layer data for those layers with a temporal dimension.
This feature need some sub modification into this project:

- Implement an algorithm to get the temporal data from capabilities when opening the filter gui
- Implement an algorithm to calculate the temporal dimension granularity

Feature business rule:

- Allow only dates between the date range from capabilities
- Calendar filter only by calculated granularity

**Comment by andre-carvalho** [comment]
The date filter tool has been fully implemented. See details on PR #26
