### ISSUE TITLE
Fix legends to DETER layers related with authentication process

### ISSUE THREAD

**Issue by andre-carvalho** [terrabrasilis/webmap#31]
The SLD style used to apply the subtitles, one for each language used in the App, must have the same layer name and a suffix for each language used, like this: <layer_name>_en and <layer_name>_pt-br. For these new layers created to standardize the DETER layer names used for anonymous and authenticated users, SLD styles remain with the old name, based on the layer used previously.
Therefore, to solve this problem, create new styles using the related layer names and assign those styles to the layers themselves in GeoServer.

**Comment by claudiobogossian** [comment]
It was create the layer style that was missing.
