### ISSUE TITLE
Legends translation

### ISSUE THREAD

**Issue by andre-carvalho** [terrabrasilis/webmap#33]
When we access the application for the first time, the language key is not set; In this context, the default language is detected in the browser configuration or predefined by default. But the map legends use the primary English language value by default. To reproduce this behavior, use an anonymous browser tab and the default language must be Portuguese.

This problem affects all versions, including production version 2.x and earlier.

**Comment by claudiobogossian** [comment]
Fixed, now it's using the legend translation according to the current webmap langague.
