### ISSUE TITLE
Translation of authentication menu

### ISSUE THREAD

**Issue by andre-carvalho** [terrabrasilis/webmap#35]
The translation of the authentication menu is not maintained.
To reproduce this behavior, we select the English language, reload the application and open the dialog box by clicking on the icon.

![oauthUI-translate](https://user-images.githubusercontent.com/11821768/82610589-0d12f500-9b95-11ea-9680-4f35b959a395.png)

**Comment by claudiobogossian** [comment]
Fixed, the problem was that the Authentication init method wasn't checking the current language on localStorage to init the Authentication menu. Changed the location of the Authentication.init() method to get the language first.
