### ISSUE TITLE
Duplicated layer int the Legal Amazon

### ISSUE THREAD

**Issue by ammaciel** [terrabrasilis/webmap#36]
There are equals layers in Legal Amazon vision, but with different names. This problem occurs only in homologation version.

Homologation version
![homologation](https://user-images.githubusercontent.com/18755189/82675134-c071fd00-9c1a-11ea-9bc6-6ca6810a3c32.png)

Production
![production](https://user-images.githubusercontent.com/18755189/82675138-c1a32a00-9c1a-11ea-91bd-9fbdc75ba92d.png)

**Comment by claudiobogossian** [comment]
Removed
