### ISSUE TITLE
Adds an extra layer over exist layer

### ISSUE THREAD

**Issue by ammaciel** [terrabrasilis/webmap#37]
The tool "Add Others Layers", add an extra layer even when already exist. This same behavior occurs in the versions of homologation and production.

Layer "Deforestation Notices since 2018" is disabled, but can still be seen in map due to extra layer
![layer](https://user-images.githubusercontent.com/18755189/82678678-63794580-9c20-11ea-8732-0eb7421aabf7.png)

**Comment by claudiobogossian** [comment]
Fixed, it wasn't removing the layer
