### ISSUE TITLE
The OAuth component broke layer-dependent tools

### ISSUE THREAD

**Issue by andre-carvalho** [terrabrasilis/webmap#43]
Some layer-dependent tools are stopped because they use some type of request based on the layer.

- Pointing over the map(GetFeatureInfo);
- On the layer toolbar - Download tool;
- On the layer toolbar - Info tool (the name of layer is wrong);
- On the layer toolbar - Time dimension;

**Comment by claudiobogossian** [comment]
Fixed on version v2.1.5
